// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SP19.P2.Web.Model;

namespace SP19.P2.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190207005004_valuesInserting2")]
    partial class valuesInserting2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SP19.P2.Web.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(30);

                    b.Property<string>("State")
                        .HasMaxLength(30);

                    b.Property<string>("StreetName")
                        .HasMaxLength(128);

                    b.Property<int>("StreetNumber");

                    b.Property<int>("Zip")
                        .HasMaxLength(5);

                    b.HasKey("AddressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MailingAddressAddressId");

                    b.Property<int?>("PaymentOptionId");

                    b.Property<int?>("RelatedUserUserId");

                    b.HasKey("CustomerId");

                    b.HasIndex("MailingAddressAddressId");

                    b.HasIndex("PaymentOptionId");

                    b.HasIndex("RelatedUserUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.LineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<int>("PerItemCost");

                    b.Property<int?>("ReceiptId");

                    b.HasKey("LineItemId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(26);

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Name = "Lunch Menu"
                        },
                        new
                        {
                            MenuId = 2,
                            Name = "Entre Menu"
                        },
                        new
                        {
                            MenuId = 3,
                            Name = "Desert Menu"
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Picture");

                    b.Property<int>("Price");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 10,
                            Description = "awesome",
                            Name = "sandwiches",
                            Picture = "www.sandwiches.com",
                            Price = 20
                        },
                        new
                        {
                            MenuItemId = 11,
                            Description = "awesome",
                            Name = "Nuggets",
                            Picture = "www.Nuggets.com",
                            Price = 40
                        },
                        new
                        {
                            MenuItemId = 12,
                            Description = "awesome",
                            Name = "taco",
                            Picture = "www.taco.com",
                            Price = 20
                        },
                        new
                        {
                            MenuItemId = 13,
                            Description = "awesome",
                            Name = "buritos",
                            Picture = "www.buritos.com",
                            Price = 20
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.MenuJoinMenuItem", b =>
                {
                    b.Property<int>("MenuId");

                    b.Property<int>("MenutItemId");

                    b.HasKey("MenuId", "MenutItemId");

                    b.HasIndex("MenutItemId");

                    b.ToTable("MenuJoinMenuItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenutItemId = 10
                        },
                        new
                        {
                            MenuId = 1,
                            MenutItemId = 11
                        },
                        new
                        {
                            MenuId = 1,
                            MenutItemId = 12
                        },
                        new
                        {
                            MenuId = 1,
                            MenutItemId = 13
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.PaymentOption", b =>
                {
                    b.Property<int>("PaymentOptionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingAddressAddressId");

                    b.Property<string>("Nickname")
                        .HasMaxLength(64);

                    b.Property<int?>("ReceiptId");

                    b.Property<string>("TokenizedCardReference")
                        .HasMaxLength(128);

                    b.HasKey("PaymentOptionId");

                    b.HasIndex("BillingAddressAddressId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("PaymentOptions");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfPayment");

                    b.Property<int?>("LineItemId");

                    b.Property<int>("PaymentAuthenticationNumber");

                    b.Property<int?>("PaymentOptionId");

                    b.Property<int>("PaymentReferenceNumber");

                    b.Property<int?>("ServerUserId");

                    b.Property<int?>("TableId");

                    b.Property<int>("Total");

                    b.HasKey("ReceiptId");

                    b.HasIndex("LineItemId");

                    b.HasIndex("PaymentOptionId");

                    b.HasIndex("ServerUserId");

                    b.HasIndex("TableId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<int?>("UserId");

                    b.HasKey("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfSeats");

                    b.Property<string>("TableType");

                    b.HasKey("TableId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            NumberOfSeats = 10,
                            TableType = "Round Type"
                        },
                        new
                        {
                            TableId = 2,
                            NumberOfSeats = 20,
                            TableType = "Bar Height Table"
                        },
                        new
                        {
                            TableId = 3,
                            NumberOfSeats = 20,
                            TableType = "Family Dining Table"
                        },
                        new
                        {
                            TableId = 4,
                            NumberOfSeats = 5,
                            TableType = "Outdoor Table"
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.TableBill", b =>
                {
                    b.Property<int>("TableBillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customer");

                    b.Property<DateTimeOffset>("EndTime");

                    b.Property<DateTimeOffset>("StartTime");

                    b.Property<int>("TableFoodItemId");

                    b.Property<int>("TableId");

                    b.HasKey("TableBillId");

                    b.HasIndex("TableFoodItemId");

                    b.HasIndex("TableId");

                    b.ToTable("TableBills");

                    b.HasData(
                        new
                        {
                            TableBillId = 50,
                            Customer = 1000,
                            EndTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 762, DateTimeKind.Unspecified).AddTicks(6381), new TimeSpan(0, -6, 0, 0, 0)),
                            StartTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 760, DateTimeKind.Unspecified).AddTicks(9810), new TimeSpan(0, -6, 0, 0, 0)),
                            TableFoodItemId = 1,
                            TableId = 1
                        },
                        new
                        {
                            TableBillId = 51,
                            Customer = 1001,
                            EndTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 762, DateTimeKind.Unspecified).AddTicks(8001), new TimeSpan(0, -6, 0, 0, 0)),
                            StartTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 762, DateTimeKind.Unspecified).AddTicks(7986), new TimeSpan(0, -6, 0, 0, 0)),
                            TableFoodItemId = 2,
                            TableId = 2
                        },
                        new
                        {
                            TableBillId = 52,
                            Customer = 1002,
                            EndTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 762, DateTimeKind.Unspecified).AddTicks(8020), new TimeSpan(0, -6, 0, 0, 0)),
                            StartTime = new DateTimeOffset(new DateTime(2019, 2, 6, 18, 50, 4, 762, DateTimeKind.Unspecified).AddTicks(8016), new TimeSpan(0, -6, 0, 0, 0)),
                            TableFoodItemId = 3,
                            TableId = 3
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.TableFoodItem", b =>
                {
                    b.Property<int>("TableFoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOrdered");

                    b.Property<int>("Discount");

                    b.Property<int>("MenuItemId");

                    b.HasKey("TableFoodItemId");

                    b.ToTable("TableFoodItems");

                    b.HasData(
                        new
                        {
                            TableFoodItemId = 1,
                            AmountOrdered = 100,
                            Discount = 10,
                            MenuItemId = 10
                        },
                        new
                        {
                            TableFoodItemId = 2,
                            AmountOrdered = 110,
                            Discount = 20,
                            MenuItemId = 11
                        },
                        new
                        {
                            TableFoodItemId = 3,
                            AmountOrdered = 119,
                            Discount = 0,
                            MenuItemId = 12
                        });
                });

            modelBuilder.Entity("SP19.P2.Web.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("Email")
                        .HasMaxLength(128);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<int>("role");

                    b.HasKey("UserId");

                    b.HasIndex("AddressId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Customer", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.Address", "MailingAddress")
                        .WithMany()
                        .HasForeignKey("MailingAddressAddressId");

                    b.HasOne("SP19.P2.Web.Model.PaymentOption", "PaymentOption")
                        .WithMany()
                        .HasForeignKey("PaymentOptionId");

                    b.HasOne("SP19.P2.Web.Model.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserUserId");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.LineItem", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.Receipt")
                        .WithMany("LineItems")
                        .HasForeignKey("ReceiptId");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.MenuJoinMenuItem", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.Menu", "Menu")
                        .WithMany("MenuJoinMenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SP19.P2.Web.Model.MenuItem", "MenuItem")
                        .WithMany("MenuJoinMenuItems")
                        .HasForeignKey("MenutItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SP19.P2.Web.Model.PaymentOption", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressAddressId");

                    b.HasOne("SP19.P2.Web.Model.Receipt")
                        .WithMany("PaymentOptions")
                        .HasForeignKey("ReceiptId");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Receipt", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.LineItem", "LineItem")
                        .WithMany()
                        .HasForeignKey("LineItemId");

                    b.HasOne("SP19.P2.Web.Model.PaymentOption", "PaymentOption")
                        .WithMany()
                        .HasForeignKey("PaymentOptionId");

                    b.HasOne("SP19.P2.Web.Model.User", "Server")
                        .WithMany()
                        .HasForeignKey("ServerUserId");

                    b.HasOne("SP19.P2.Web.Model.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.Role", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SP19.P2.Web.Model.TableBill", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.TableFoodItem")
                        .WithMany("TableBills")
                        .HasForeignKey("TableFoodItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SP19.P2.Web.Model.Table")
                        .WithMany("TableBills")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SP19.P2.Web.Model.User", b =>
                {
                    b.HasOne("SP19.P2.Web.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
